[project]
name = "graph-repairing"
version = "0.0.1"
description = ""
readme = "README.md"
authors = [
  {name = "Your Name", email = "your@example.com"},
]
requires-python = ">=3.12"
dependencies = [
    "easydict>=1.13",
    "ipykernel>=7.1.0",
    "neo4j>=6.0.3",
]
